import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {execFileSync} from 'node:child_process';
import {loadConfig} from '../lib/config.ts';
import {validate} from '../lib/model.ts';
import {compose,tree,changedRows,snapshots} from '../lib/ui.ts';
import {job} from '../lib/run.ts';
const presets=path.resolve(import.meta.dirname,'../presets');
function expression(file:string):any {return new Function('load','"use strict";return ('+fs.readFileSync(file,'utf8')+'\n)')( (child:string)=>expression(path.resolve(path.dirname(file),child)) );}
function run(op:any,cwd:string,kind:any){return validate(kind,op.parse(execFileSync(op.command,op.args,{cwd,encoding:'utf8',maxBuffer:4*1024*1024})));}
function loader(dir:string){return {getPluginConfig:()=>({adapterConfig:'config.js'}),getConfigDir:()=>dir,pathIsAbsolute:path.isAbsolute,pathJoin:path.join,pathDirname:path.dirname,localPath:(p:string)=>p,readFile:(p:string)=>fs.existsSync(p)?fs.readFileSync(p,'utf8'):null} as any;}
test('trusted expressions preserve closures/inline lambdas, relative load, namespace/reload and syntax errors',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vcs-config-'));try {fs.writeFileSync(path.join(dir,'preset.js'),'(()=>{let suffix="closure";return {name:"Preset",capabilities:{sources:["unstaged"],history:false,content:false,blame:false},diff:()=>({command:"printf",args:[suffix],parse:s=>({files:[]})})}})()');fs.writeFileSync(path.join(dir,'config.js'),'({adapters:[load("./preset.js")]})');assert.deepEqual(loadConfig(loader(dir))[0].diff({} as any).args,['closure']);fs.writeFileSync(path.join(dir,'config.js'),'({adapters:[{...load("./preset.js"),name:"Edited inline",diff:({source})=>({command:"printf",args:[source],parse:s=>({files:[]})})}]})');const a=loadConfig(loader(dir))[0];assert.equal(a.name,'Edited inline');assert.equal(a.diff({source:'staged'} as any).args[0],'staged');fs.writeFileSync(path.join(dir,'config.js'),'({');assert.throws(()=>loadConfig(loader(dir)),SyntaxError);fs.writeFileSync(path.join(dir,'config.js'),'load("./config.js")');assert.throws(()=>loadConfig(loader(dir)),/Cyclic/);assert.throws(()=>loadConfig({...loader(dir),getPluginConfig:()=>({})}),/adapterConfig/);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('schema rejects unsafe paths, duplicate ids, malformed hunks and labels; empty explicit',()=>{
 assert.deepEqual(validate('diff',{files:[]}),{files:[]});const f={id:'x',oldPath:null,newPath:'safe',status:'added',added:1,deleted:0,binary:false,before:null,after:{path:'safe',revision:'r'},hunks:[{oldStart:0,oldCount:0,newStart:0,newCount:1,ops:'+'}]};assert.doesNotThrow(()=>validate('diff',{files:[f]}));for(const p of ['../x','/x','a/../x','a\0b'])assert.throws(()=>validate('diff',{files:[{...f,newPath:p}]}));assert.throws(()=>validate('diff',{files:[f,f]}));assert.throws(()=>validate('diff',{files:[{...f,hunks:[{...f.hunks[0],ops:'-'}]}]}));assert.throws(()=>validate('blame',{ranges:[{startLine:1,endLine:0,label:'x'}]}));assert.throws(()=>validate('history',[{revision:'r',label:'multi\nline'}]));
});
test('real temporary Git all four ops: root, first-parent merge, staged/index/disk, rename/delete/binary/Unicode, subdir',()=>{
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'vcs-git-'));const git=(...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8'}).trim();const a=expression(path.join(presets,'git.js'));try{
 git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('config','commit.gpgsign','false');fs.mkdirSync(path.join(cwd,'src'));fs.writeFileSync(path.join(cwd,'src/界 é.txt'),'one\ntwo\n');fs.writeFileSync(path.join(cwd,'delete.txt'),'gone\n');fs.writeFileSync(path.join(cwd,'rename.txt'),'rename\n');git('add','.');git('commit','-qm','root');const root=git('rev-parse','HEAD');const rootDiff=run(a.diff({cwd,source:'commit',revision:root}),cwd,'diff');assert(rootDiff.files.every((f:any)=>f.before===null));
 fs.writeFileSync(path.join(cwd,'src/界 é.txt'),'one\nINDEX\n');git('add','src/界 é.txt');fs.writeFileSync(path.join(cwd,'src/界 é.txt'),'one\nDISK\n');const staged=run(a.diff({cwd,source:'staged',revision:null}),cwd,'diff');const unstaged=run(a.diff({cwd,source:'unstaged',revision:null}),cwd,'diff');assert.equal(run(a.content({cwd,...staged.files[0].after}),cwd,'content').text,'one\nINDEX\n');assert.equal(run(a.content({cwd,...unstaged.files[0].after}),cwd,'content').text,'one\nDISK\n');assert.equal(run(a.content({cwd,...unstaged.files[0].before}),cwd,'content').text,'one\nINDEX\n');const sub=path.join(cwd,'src');const d=run(a.diff({cwd:sub,source:'unstaged',revision:null}),sub,'diff');assert.equal(d.files[0].newPath,'界 é.txt');assert.equal(run(a.content({cwd:sub,...d.files[0].before}),sub,'content').text,'one\nINDEX\n');assert(run(a.blame({cwd,path:'src/界 é.txt'}),cwd,'blame').ranges.some((r:any)=>r.label==='Uncommitted'));
 git('mv','rename.txt','renamed.txt');git('rm','-q','delete.txt');fs.writeFileSync(path.join(cwd,'binary.bin'),Buffer.from([0,1,2]));fs.symlinkSync('src/界 é.txt',path.join(cwd,'link'));git('add','.');const multi=run(a.diff({cwd,source:'staged',revision:null}),cwd,'diff');assert(multi.files.some((f:any)=>f.status==='renamed'));assert(multi.files.some((f:any)=>f.status==='deleted'));assert(multi.files.some((f:any)=>f.binary));assert(multi.files.some((f:any)=>f.metadata.some((m:string)=>m.includes('120000'))));const contents=new Map();for(const f of multi.files)if(!f.binary)contents.set(f.id,[f.before?run(a.content({cwd,...f.before}),cwd,'content').text:'',f.after?run(a.content({cwd,...f.after}),cwd,'content').text:'']);const stream=compose(multi,contents);assert.equal(stream.anchors.size,multi.files.length);assert(stream.next.includes('FILE binary.bin'));assert(stream.old.includes('FILE renamed.txt'));
 git('commit','-qm','second');fs.unlinkSync(path.join(cwd,'link'));fs.symlinkSync('missing-target',path.join(cwd,'link'));const linkDiff=run(a.diff({cwd,source:'unstaged',revision:null}),cwd,'diff');const link=linkDiff.files.find((f:any)=>f.newPath==='link');assert.equal(run(a.content({cwd,...link.after}),cwd,'content').text,'missing-target');fs.unlinkSync(path.join(cwd,'link'));fs.symlinkSync('src/界 é.txt',path.join(cwd,'link'));const first=git('rev-parse','HEAD');git('checkout','-qb','side');fs.writeFileSync(path.join(cwd,'side.txt'),'side\n');git('add','.');git('commit','-qm','side');git('checkout','-q','-');fs.writeFileSync(path.join(cwd,'main.txt'),'main\n');git('add','.');git('commit','-qm','main');git('merge','--no-ff','-qm','merge','side');const merge=run(a.diff({cwd,source:'commit',revision:'HEAD'}),cwd,'diff');assert.deepEqual(merge.files.map((f:any)=>f.newPath),['side.txt']);assert(run(a.history({cwd,limit:3}),cwd,'history').length===3);assert.doesNotThrow(()=>run(a.content({cwd,path:'main.txt',revision:'HEAD'}),cwd,'content'));assert.equal(run(a.diff({cwd,source:'unstaged',revision:null}),cwd,'diff').files.length,0);assert(first);git('checkout','-qb','conflicting');fs.writeFileSync(path.join(cwd,'main.txt'),'conflicting\n');git('add','.');git('commit','-qm','conflict side');git('checkout','-q','-');fs.writeFileSync(path.join(cwd,'main.txt'),'different\n');git('add','.');git('commit','-qm','conflict main');assert.throws(()=>git('merge','--no-ff','-m','conflict','conflicting'));const unmerged=run(a.diff({cwd,source:'unstaged',revision:null}),cwd,'diff');assert.equal(unmerged.files[0].status,'unmerged');assert.equal(run(a.content({cwd,...unmerged.files[0].before}),cwd,'content').text,'different\n');
 }finally{fs.rmSync(cwd,{recursive:true,force:true});}
});
test('Arc recorded read-only schemas normalize separately from Git; not live Arc writes',()=>{
 const a=expression(path.join(presets,'arc.js'));const dir=path.join(import.meta.dirname,'fixtures');for(const [kind,file,op] of [['history','arc-history.json',a.history({limit:1})],['blame','arc-blame.json',a.blame({path:'.arcignore'})],['diff','arc-diff.patch',a.diff({source:'commit',revision:'47c1d33914b557f98629a64c904871373e60c983'})]] as any[]) {assert.doesNotThrow(()=>validate(kind,op.parse(fs.readFileSync(path.join(dir,file),'utf8'))));}
});
test('runner validates argv, bounded file-backed read, parser errors, cancellation and deadline',async()=>{
 const cwd='/tmp';let kills=0,discard=0,reads=0;let output='{"files":[]}';let args:any[]=[];const editor:any={pathIsAbsolute:path.isAbsolute,getAuthorityLabel:()=>'',scratchCreate:()=> 'token',scratchPath:()=>'/tmp/token',scratchDiscard:()=>{discard++;},pathJoin:path.join,localPath:(p:string)=>p,fileStat:()=>({size:output.length}),delay:(ms:number)=>new Promise(r=>setTimeout(r,Math.min(ms,2))),killProcess:()=>{kills++;return true;},activeWindow:()=>1,openMachine:async()=>({readFilePrefixes:async(r:any)=>{reads++;assert.equal(r[0].maxBytes,4*1024*1024+1);return [{text:output}];},close:async()=>true}),spawnProcess:(...v:any[])=>{args=v;const h:any=Promise.resolve({exit_code:0,stderr:'',stdout:v[1][0]==='--version'?'timeout (GNU coreutils) 9.4\n':''});h.processId=9;h.kill=async()=>{kills++;return true;};return h;}};
 const builder=()=>({command:'printf',args:['%s','x'],parse:JSON.parse});assert.deepEqual(await job(editor).run('diff',builder,cwd),{files:[]});assert.equal(args[3],'/tmp/token/stdout');assert.equal(reads,1);assert.equal(discard,1);assert.deepEqual(args.slice(0,3),['timeout',['--signal=TERM','--kill-after=1s','15s','printf','%s','x'],cwd]);await assert.rejects(job(editor).run('diff',()=>({...builder(),args:['\0']}),cwd),/argv/);output='{';await assert.rejects(job(editor).run('diff',builder,cwd),SyntaxError);const cancelled=job(editor);cancelled.cancel();await assert.rejects(cancelled.run('diff',builder,cwd),/Cancelled/);
 editor.spawnProcess=()=>{const h:any=new Promise(r=>setTimeout(()=>r({exit_code:124,stderr:'',stdout:''}),10));h.processId=12;h.kill=()=>{throw new Error('Must not kill timeout supervisor');};return h;};await assert.rejects(job(editor,1).run('diff',builder,cwd),/timed out/);await new Promise(r=>setTimeout(r,15));
 const unsupported={...editor,spawnProcess:async()=>({exit_code:0,stdout:'BusyBox timeout',stderr:''})};await assert.rejects(job(unsupported,15000,'unsupported-timeout').run('diff',builder,cwd),/GNU coreutils timeout required/);
});

test('review fixes: one-column rows/anchors, mixed markers, interleaved hierarchy and early snapshot budget',async()=>{
 const file=(id:string,p:string)=>({id,oldPath:p,newPath:p,status:'modified',added:1,deleted:1,binary:false,before:{path:p,revision:'before'},after:{path:p,revision:'after'},hunks:[]});
 const files=[file('one','a/first'),file('two','b/second'),file('three','a/third')];
 const diff:any={files};const view:any=tree(diff,'three','',0,null);const widget=view.children[1];assert.deepEqual(widget.itemKeys,['dir:a','one','three','dir:b','two']);assert.equal(widget.nodes[0].text.text,'a');assert.deepEqual(widget.nodes.map((n:any)=>n.depth),[0,1,1,0,1]);
 const h={oldStart:0,oldCount:5,newStart:0,newCount:4,ops:' -+ - '};assert.deepEqual(changedRows(h),[{line:1,kind:'modified'},{line:3,kind:'deleted'}]);files[0].hunks=[h] as any;
 const stream=compose(diff,new Map([['one',['a\nb\nc\nd\ne\n','a\nB\nc\ne\n']]]));assert(stream.unified.some(e=>e.text==='- b\n'));assert(stream.unified.some(e=>e.text==='+ B\n'));assert(stream.unified.some(e=>e.text==='- d\n'));assert.deepEqual(stream.rows[stream.unified.findIndex(e=>e.text==='+ B\n')],[null,3]);assert.equal(stream.anchors.size,3);
 let calls=0;await assert.rejects(snapshots(diff,async()=>{calls++;return 'x'.repeat(4*1024*1024);}),/total content limit/);assert.equal(calls,2);
});
test('real Git quoted UTF8 percent/control paths survive noprefix for diff and show',()=>{
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'vcs-paths-'));const git=(...args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8'});const a=expression(path.join(presets,'git.js'));
 try{git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');git('config','commit.gpgsign','false');git('config','diff.noprefix','true');const paths=['界%20.txt','tab\t界.txt','line\n界.txt','space 界.txt','😀%ab.txt'];for(const p of paths)fs.writeFileSync(path.join(cwd,p),'before\n');git('add','.');git('commit','-qm','root');for(const p of paths)fs.writeFileSync(path.join(cwd,p),'after\n');git('add','.');for(const source of ['staged','commit']){const d=run(a.diff({source,revision:source==='commit'?'HEAD':null}),cwd,'diff');assert.deepEqual(new Set(d.files.map((f:any)=>f.newPath)),new Set(paths));for(const f of d.files)assert(run(a.content({...f.after}),cwd,'content').text);}const patch=expression(path.join(presets,'patch.js'));assert.throws(()=>patch('diff --git "x/wrong" "b/right"\n','a','b'),/prefix/);
 }finally{fs.rmSync(cwd,{recursive:true,force:true});}
});
